version: '3.8'

services:
  app:
    build: .
    command: python -m src.app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - celery_worker

  celery_worker:
    build: .
    command: celery -A src.tasks worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0  

  redis:
    image: "redis:alpine"
    ports:
    - "6379:6379"