version: '3.8'

services:
  app:
    build: .
    container_name: flask_app
    command: flask run --host=0.0.0.0
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    depends_on:
      - redis
      - celery

  celery:
    build: .
    container_name: celery_worker
    command: celery -A src.tasks worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
  
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"